FROM python:3.7-slim

RUN mkdir /app

#WORKDIR /app

COPY api_yamdb/requirements.txt api_yamdb/app/
#COPY . /app/
RUN pip3 install -r api_yamdb/app/requirements.txt --no-cache-dir

COPY . /app/



CMD ["gunicorn", "api_yamdb.wsgi:application", "--bind", "0:8000" ] 





# WORKDIR /app

# COPY requirements.txt /app

# RUN pip3 install -r /app/requirements.txt --no-cache-dir

# COPY . .

# CMD ["gunicorn", "api_yamdb.wsgi:application", "--bind", "0:8000" ] 

